### ISSUE TITLE
[Feat] 메인 뷰 제작

### ISSUE THREAD

**Issue by wonniiii** [DeveloperAcademy-POSTECH/MC2-Team5-Snooze#1]
## 🛠 Issue
1. 앱 상에서 위치가 멀어지면 시간 카운트 시작 
2. 카운트 시작해서 10분마다 한번씩 위젯에 업데이트 알림
3. 위젯은 10분마다 시간을 바꾸고, 위젯 안의 이미지도 10분마다 변경 (테스트용)
4. 잠금화면 위젯 - 출근한지 1~2시간 (시간마다 변경)

## 📝 To-do

- [x] main 브랜치에 위젯, UserNotifications, CoreLocation 추가 후 세팅
- [ ] 위젯 UI 세팅
- [ ] 위젯 provider 세팅
- [ ] 잠금화면 위젯 세팅
