### ISSUE TITLE
[Refactor] 로컬 노티피케이션 관련 테스트 및 디테일 작업

### ISSUE THREAD

**Issue by poodlepoodle** [DeveloperAcademy-POSTECH/MC2-Team5-Snooze#30]
## 🛠 Issue
- 로컬 노티피케이션 기능에 대해서 테스트하고 전체 키 플로우에 맞춰 작동하도록 하기 위해 코드 리팩토링을 진행합니다.

## 📝 To-do

- [x] 백그라운드에서 알림이 잘 오는지 확인
- [x] 터미네이트 상태(아예 백그라운드)에서 알림이 잘 오는지 확인
- [x] 알림 콘텐츠 연결 (메시지 내용)
- [x] 커뮤니케이션 노티피케이션(카톡 스타일의 푸시 알림)으로 리팩토링 적용
