### ISSUE TITLE
[Chore] 기타 작업

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MC2-Team5-Snooze#31]
## 🛠 Issue
여러 버그 및 기타 수정

## 📝 To-do

- [x] 등록화면 → 메인으로 넘어갔을 때 버튼들 동작안함
- [x] Realm, UserDefault 확인
- [x] info.plist 메시지
