### ISSUE TITLE
[Refactor] 네트워크 구조 수정 및 커스텀 뷰 제작

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MC2-Team5-Snooze#42]
## 🛠 Issue
네트워크 구조 수정 및 커스텀 뷰 제작

## 📝 To-do

- [ ] All Custom View
- [x] RealmManager Repository set
- [ ] 주석 제거 및 코드 라인 정리
